=== OpenLMIS/openlmis-stockmanagement/src/main/resources/schemas/reason.json
{
  "type": "object",
  "$schema": "http://json-schema.org/draft-04/schema",
  "description": "The reason in line item.",
  "properties": {
    "isFreeTextAllowed": {
      "type": "boolean"
    },
    "name": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "id": {
      "type": [
        "null",
        "string"
      ]
    },
    "reasonType": {
      "type": "string",
      "enum": [
        "CREDIT",
        "DEBIT",
        "BALANCE_ADJUSTMENT"
      ]
    },
    "reasonCategory": {
      "type": "string",
      "enum": [
        "TRANSFER",
        "ADJUSTMENT",
        "PHYSICAL_INVENTORY"
      ]
    }
  },
  "required": [
    "isFreeTextAllowed",
    "name",
    "description",
    "reasonType",
    "reasonCategory"
  ]
}

=== OpenLMIS/openlmis-stockmanagement/demo-data/stockmanagement.stock_card_line_item_reasons.json
[
  {
    "id": "e3fc3cf3-da18-44b0-a220-77c985202e06",
    "name": "Transfer In",
    "description": "Transfer In",
    "reasonCategory": "TRANSFER",
    "reasonType": "CREDIT",
    "isFreeTextAllowed": false
  },
  {
    "id": "c1fc3cf3-da18-44b0-a220-77c985202e06",
    "name": "Transfer Out",
    "description": "Transfer Out",
    "reasonCategory": "TRANSFER",
    "reasonType": "DEBIT",
    "isFreeTextAllowed": false
  },
  {
    "id": "279d55bd-42e3-438c-a63d-9c021b185dae",
    "name": "Clinic return",
    "description": "Clinic return",
    "reasonCategory": "ADJUSTMENT",
    "reasonType": "CREDIT",
    "isFreeTextAllowed": true
  },
  {
    "id": "5b09202e-b8a7-4f77-9e0e-8156f8efc613",
    "name": "Damage",
    "description": "Damage",
    "reasonCategory": "ADJUSTMENT",
    "reasonType": "DEBIT",
    "isFreeTextAllowed": true
  }
]
